Filtering Method 

In [ ]:
Filter all numbers greater than 5
Get all even numbers
Get all odd numbers
Filter numbers less than 10
Remove all zeros from array
get a number form 10 and 20
Get elements divisible by 3
Replace all values > 50 with 0
Extract negative numbers only
Get numbers not equal to 5

In [11]:
import numpy as np
# Filter all numbers greater than 5 
"""arr = np.arange(1,20)
result = []
for i in arr:
    if i > 5:
        result.append(i)
print(result)
"""
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])
result = arr[arr > 5]
print(result)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18]


In [6]:
result

[np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9),
 np.int64(10),
 np.int64(11),
 np.int64(12),
 np.int64(13),
 np.int64(14),
 np.int64(15),
 np.int64(16),
 np.int64(17),
 np.int64(18),
 np.int64(19)]

In [14]:
# Get all even numbers
arr = np.arange(1 , 100)
result = arr[arr%2==0]
print(result)


[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96
 98]


In [20]:
# Get all odd  numbers
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
rsult =arr[arr % 2 != 0]
print(rsult)

[ 1  3  5  7  9 11 13 15 17 19]


In [22]:
# Filter numbers less than 10
nums = np.arange(1 , 50)
result = nums[nums < 10]
print(result)

[1 2 3 4 5 6 7 8 9]


In [30]:
# Remove all zeros from array
arr = np.array([1 ,2 ,3 ,4 ,5 , 6, 7,8 , 0 , 0 , 0])
result = arr[arr!=0]
print(result)

[1 2 3 4 5 6 7 8]


In [50]:
# Get elements divisible by 3a
arr = np.array(input('Input a number').split(),dtype=int)
rslt = ['yes '  if x%3==0 else 'no' for x in arr]
print(rslt)

Input a number 14


['no']


In [53]:
# Replace all values > 50 with 0
arr = np.array([10 , 20 , 30,40,50,60,70,80])
result = arr[arr > 40] = 0
print(result , arr)

0 [10 20 30 40  0  0  0  0]


In [55]:
result = arr[arr != 20]
print(result)

[10 30 40  0  0  0  0]


In [57]:
#Extract negative numbers only
arr = np.array([1,2,3,4,5,6,7,8,9,10 , -1 , -2 , -3 , -4])
result = arr[arr < 0]
print(result)

[-1 -2 -3 -4]


In [61]:
# Get numbers not equal to 5
arr = np.array(input('Enter a numeber').split(),dtype=int)
result = ['equal' if x == 5 else 'not equal ' for x in arr]
print(result)

Enter a numeber 6


['not equal ']


In [65]:
# get a number form 10 and 20
arr = np.array([5,10,15,20,25,30,35,40,45,50])
rslt = arr[(arr>10)&(arr<20)]
print(rslt)


[]
